server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fwfurtado/micro-8744/tree/master/config-files
          search-paths: config-files
