server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/fwfurtado/micro-8744/
          repos:
            prod:
              pattern:
                - "*/prod"
              search-paths: config-files/prod
            qa:
              pattern:
                - "*/qa"
              search-paths: config-files/qa

