server:
  port: 8010

spring:
  application:
    name: distancia

caelum:
  system:
    url: http://localhost
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
